[package]
name = "zksync_prover_fri_utils"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zksync_object_store = { path = "../../core/lib/object_store", version = "1.0" }

circuit_definitions = { git = "https://github.com/matter-labs/zkevm_test_harness.git", branch = "v1.4.0", features = ["log_tracing"]}

serde = { version = "1.0", features = ["derive"] }
