[package]
name = "vm_virtual_blocks"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
zk_evm = { git = "https://github.com/matter-labs/zk_evm.git", branch = "v1.3.3" }

zksync_config = { path = "../../lib/config" }
zksync_types = { path = "../../lib/types" }
zksync_utils = { path = "../../lib/utils" }
zksync_state = { path = "../../lib/state" }

vm_latest = { path = "../../lib/vm", package = "vm" }

anyhow = "1.0"
hex = "0.4"
itertools = "0.10"
metrics = "0.20"
once_cell = "1.7"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["time"] }
zksync_test_account = { path = "../../lib/test_account" }
ethabi = "18.0.0"
zksync_eth_signer = { path = "../../lib/eth_signer" }
zksync_contracts = { path = "../../lib/contracts" }
