version: '3.2'
services:
# basic zk environment (without geth and postgres)
# Used mostly for CI jobs that do compilation or linting.
  zk:
    image: "matterlabs/zk-environment:latest2.0-lightweight"
    security_opt:
      - seccomp:unconfined
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
      - SCCACHE_GCS_SERVICE_ACCOUNT=gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com
      - SCCACHE_ERROR_LOG=/tmp/sccache_log.txt
      - SCCACHE_GCS_RW_MODE=READ_WRITE
      - CI=1
      - GITHUB_WORKSPACE=$GITHUB_WORKSPACE
    env_file:
      - ./.env
    extra_hosts:
      - "host:host-gateway"