database_url = "postgres://postgres@postgres/zksync_local"
test_database_url = "postgres://postgres@host:5433/zksync_local_test"
database_prover_url="postgres://postgres@localhost/zksync_local_prover"
test_database_prover_url="postgres://postgres@localhost:5433/zksync_local_prover_test"

# for loadtest
l1_rpc_address = "http://geth:8545"

[eth_client]
web3_url = "http://geth:8545"

[chain.state_keeper]
miniblock_iteration_interval = 50

