[package]
name = "storage_logs_dedup_migration"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "storage_logs_dedup_migration"
path = "src/main.rs"

[[bin]]
name = "storage_logs_dedup_migration_consistency_checker"
path = "src/consistency.rs"

[dependencies]
tokio = { version = "1" }
zksync_server_dal = { path = "../../lib/server_dal" }
zksync_types = { path = "../../lib/types" }
zksync_config = { path = "../../lib/config" }
zksync_env_config = { path = "../../lib/env_config" }
zksync_db_connection = {path = "../../lib/db_connection"}

clap = { version = "4.2.4", features = ["derive"] }
