[workspace]
members = [
    # lib
    "prover_fri_utils",

    # binaries
    "prover",
    "circuit_synthesizer",
    "setup_key_generator_and_server",
    "witness_generator",
    "vk_setup_data_generator_server_fri",
    "prover_fri"
]

resolver = "2"

# for `perf` profiling
[profile.perf]
inherits = "release"
debug = true
