[database]
# Path to the directory that contains RocksDB with VM state cache.
state_keeper_db_path="./db/main/state_keeper"
# Path to the directory that contains RocksDB backups for Merkle tree.
merkle_tree_backup_path="./db/main/backups"
# Path to the directory that contains RocksDB with Merkle tree.
new_merkle_tree_ssd_path="./db/main/tree"
backup_count=5
backup_interval_ms=60000
max_block_batch=100
# Amount of open connections to the database.
pool_size=50
