[package]
name = "zksync_prover_dal"
version = "0.1.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-era"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]

[dependencies]
zksync_types = { path = "../../core/lib/types" }
zksync_utils = { path = "../../core/lib/utils" }
zksync_health_check = { path = "../../core/lib/health_check" }
zksync_db_utils = { path = "../../core/lib/db_utils"}

sqlx = { version = "0.5.13", default-features = false, features = [
    "runtime-tokio-native-tls",
    "macros",
    "postgres",
    "bigdecimal",
    "chrono",
    "json",
    "offline",
    "migrate",
    "ipnetwork",
] }
anyhow = "1.0"
itertools = "0.10.1"
tokio = { version = "1", features = ["full"] }
url = "2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bigdecimal = "0.2.2"
bincode = "1"
tracing = "0.1"
strum = { version = "0.24", features = ["derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
