name: Build Image from tag
on:
  workflow_call:
    inputs:
      tag_name:
        description: "Tag of an image to built"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag of an image to built"
        type: string
        required: true
  push:
    branches:
      - ci-core-multiarch-another

concurrency: docker-build

jobs:
  setup:
    name: Setup
    runs-on: [ubuntu-latest]
    outputs:
      image_tag_suffix: ${{ steps.set.outputs.image_tag_suffix }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: Generate output with git tag
        id: set
        run: |
          git_tag=""
          if [[ -z "${{ inputs.tag_name }}" ]]; then
            git_tag="${GITHUB_REF#refs/*/}"
          else
            git_tag="${{ inputs.tag_name }}"
          fi
          version=$(cut -d "-" -f2 <<< ${git_tag})
          echo "image_tag_suffix=${version}" >> $GITHUB_OUTPUT


  build-push-core-images:
    name: Build and push image
    needs: [setup]
    uses: ./.github/workflows/build-core-template.yml
    if: contains(github.ref_name, 'core')
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_tag: ${{ needs.setup.outputs.image_tag }}-arm-experimental
      image_tag_suffix: ${{ needs.setup.outputs.image_tag_suffix }}-arm-experimental
