name: Local Node - Build docker image
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag of a built image to deploy (latest2.0 by default)"
        type: string
        required: false
        default: "latest2.0"
      era_contract_version:
        description: "Version of era-contracts which should be use"
        type: string
        required: false
        default: "main-6250292"

jobs:
  build-images:
    name: Local Node - Build and Push Docker Image
    runs-on: [matterlabs-ci-runner]
    env:
      CONTRACT_VERSION: ${{ inputs.era_contract_version }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo CI=1 >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo CI=1 >> .env
          echo IN_DOCKER=1 >> .env

      - name: Download contracts
        run: |
          mkdir -p ./contracts
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/l1-contracts.tar.gz
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/l2-contracts.tar.gz
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/system-contracts.tar.gz
          
          tar -xf l1-contracts.tar.gz -C ./contracts
          tar -xf l2-contracts.tar.gz -C ./contracts
          tar -xf system-contracts.tar.gz -C ./contracts

      - name: start-services
        run: |
          mkdir -p ./volumes/postgres
          docker compose up -d zk postgres

      - name: init
        run: |
          ci_run git config --global --add safe.directory /usr/src/zksync
          ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
          ci_run git config --global --add safe.directory /usr/src/zksync/contracts/system-contracts
          ci_run git config --global --add safe.directory /usr/src/zksync/contracts

          ci_run zk
          ci_run zk run yarn
          ci_run cp etc/tokens/{test,localhost}.json
          ci_run zk compiler all

      - name: update-image
        run: |
          ci_run docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          ci_run zk docker build server-v2
          ci_run gcloud auth configure-docker us-docker.pkg.dev -q
          ci_run zk docker push local-node --custom-tag ${{ inputs.image_tag }}
