name: publish zk-rust-nightly-environment docker image

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "docker/zk-rust-nightly-environment/Dockerfile"
      - ".github/workflows/rust-nightly-environment.publish.yml"
  workflow_dispatch:
    branches:
      - "main"

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          context: .
          push: true
          tags: "matterlabs/zksync_rust:nightly"
          file: docker/zk-rust-nightly-environment/Dockerfile
          no-cache: true
