name: Push main branch VM benchmarks to Prometheus

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Disable simultaneous deployments into a single environment
concurrency: vm-benchmarks

jobs:
  vm-benchmarks:
    name: Run VM benchmarks
    runs-on: [matterlabs-ci-runner]
    env:
      CONTRACT_VERSION: "main-6250292"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: setup-env
        run: |
          echo PUSH_VM_BENCHMARKS_TO_PROMETHEUS=1 >> .env

          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: Download contracts
        run: |
          mkdir -p ./contracts
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/l1-contracts.tar.gz
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/l2-contracts.tar.gz
          curl -LO https://github.com/matter-labs/era-contracts/releases/download/${CONTRACT_VERSION}/system-contracts.tar.gz
          
          tar -xf l1-contracts.tar.gz -C ./contracts
          tar -xf l2-contracts.tar.gz -C ./contracts
          tar -xf system-contracts.tar.gz -C ./contracts

      - name: init
        run: |
          docker compose up -d zk
          ci_run zk

      - name: run benchmarks
        run: |
          ci_run cargo bench --package vm-benchmark --bench diy_benchmark
          ci_run cargo bench --package vm-benchmark --bench iai | tee iai-result
          ci_run cargo run --package vm-benchmark --bin iai_results_to_prometheus --release < iai-result
